package repositories.impl;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import domain.Person;
import domain.User;
import repositories.IPersonRepository;
import repositories.IRepository;
import unitofwork.IUnitOfWork;

public class PersonRepository extends Repository<Person> implements IPersonRepository{

	protected PersonRepository(Connection connection,
			IEntityBuilder<Person> builder, IUnitOfWork uow) {
		super(connection, builder, uow);
	}

	@Override
	protected void setUpUpdateQuery(Person entity) throws SQLException {
		update.setString(1, entity.getFirstName());
		update.setString(2, entity.getSurname());
		update.setString(3, entity.getPesel());
		update.setString(4, entity.getAddress());
		update.setInt(5, entity.getId());
	}

	@Override
	protected void setUpInsertQuery(Person entity) throws SQLException {
		insert.setString(1, entity.getFirstName());
		insert.setString(2, entity.getSurname());
		insert.setString(3, entity.getPesel());
		insert.setString(4, entity.getAddress());
	}

	@Override
	protected String getTableName() {
		return "person";
	}

	@Override
	protected String getUpdateQuery() {
		return "update person set (firstname,surname,pesel,address)=(?,?,?,?)"
				+ "where id=?";
	}

	@Override
	protected String getInsertQuery() {
		return "insert into person(firstname,surname,pesel,address) values(?,?,?,?)";
	}

	@Override
	protected String getCreateTableQuery() {
		return "CREATE TABLE IF NOT EXISTS person("
				+ "id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "firstname VARCHAR(40)," 
				+ "surname VARCHAR(40)," 
				+ "pesel VARCHAR(12)," 
				+ "address VARCHAR(255)" 
				+ ")";
	}

	@Override
	public List<Person> withSurname(String surname) {
		String selectBySurnameSql="SELECT * FROM "
				+ getTableName()
				+ "WHERE surname = ?";
		PreparedStatement selectPerson;
		ResultSet rs;
		List<Person> list = new ArrayList<>();
		try {
			selectPerson = connection.prepareStatement(selectBySurnameSql);
			selectPerson.setString(1, surname);
			rs = selectPerson.executeQuery();
			while (rs.next()){
				list.add(builder.build(rs));
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return list;
	}
	
}