package repositories.impl;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import repositories.IPrivilegeRepository;
import unitofwork.IUnitOfWork;
import domain.Privilege;
import domain.Role;

public class PrivilegeRepository extends Repository<Privilege> implements IPrivilegeRepository{

	protected PrivilegeRepository(Connection connection,
			IEntityBuilder<Privilege> builder, IUnitOfWork uow) {
		super(connection, builder, uow);
	}

	@Override
	protected void setUpUpdateQuery(Privilege entity) throws SQLException {
		update.setString(1, entity.getName());
		update.setInt(2, entity.getId());
	}

	@Override
	protected void setUpInsertQuery(Privilege entity) throws SQLException {
		insert.setString(1, entity.getName());
	}

	@Override
	protected String getTableName() {
		return "privileges";
	}

	@Override
	protected String getUpdateQuery() {
		return "update "+ getTableName() +" set (name)=(?) where id=?;";
	}

	@Override
	protected String getInsertQuery() {
		return "insert into "+ getTableName() +"(name) values(?)";
	}

	@Override
	protected String getCreateTableQuery() {
		return "CREATE TABLE IF NOT EXISTS privileges("
				+ "id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "name VARCHAR(20) UNIQUE" 
				+ ")";
	}

	@Override
	public List<Privilege> withName(String name) {
		String selectByNameSql="SELECT * FROM "
				+ getTableName()
				+ " WHERE name = ?";
		PreparedStatement selectPrivilege;
		ResultSet rs;
		List<Privilege> list = new ArrayList<>();
		try {
			selectPrivilege = connection.prepareStatement(selectByNameSql);
			selectPrivilege.setString(1, name);
			rs = selectPrivilege.executeQuery();
			while (rs.next()){
				list.add(builder.build(rs));
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return list;
	}

}
